### ISSUE TITLE
request about python makes command palette unresponsive

### ISSUE THREAD

**Issue by psychonaute** [mre/vscode-snippet#97] opened 2021-05-13 09:38 UTC
When searching for a snippet in any language other than python, it works as intended and return meaningful results.

But when doing the same for python language though, no matter the keywords, it always return the same result:

```
#  Does Python have a ternary conditional operator?
#  
#  Yes, it was [added][1] in version 2.5. The expression syntax is:

a if condition else b
...
```
Then the command palette becomes unresponsive and I need to reload the window.

python is the language i use the most and It was working before without any issue. 

I tried to 

- uninstall-reinstall the extension
- delete the `..\.vscode\extensions\vscode-snippet.snippet-0.8.1` folder

Can't make it to work 😿 

```
Vscode: 1.56.1 (system setup)
vscode-snippet:  0.8.1
OS: Windows_NT x64 10.0.18363
```

**Comment by psychonaute** [comment] 2021-05-14 05:08
The issue disappear if I uninstall ms-python extension.

**Comment by mre** [comment] 2021-05-14 09:59
That's really odd. I can reproduce the issue on my machine.
It did work in the past, because I always had the Python extension installed, so maybe something changed in the ms-python extension? 🤔

**Comment by psychonaute** [comment] 2021-05-16 03:30
same here. And couldn't find any useful log, pointing at the culprit 🔎

**Comment by mre** [comment] 2021-05-19 11:59
I was trying to run this through a debugger to see what's going on, but I got sidetracked with other things. If you find the time, that could be an option.

**Comment by janosimas** [comment] 2021-06-04 09:41
I have the same issue with rust

**Comment by mre** [comment] 2022-07-26 21:52
Tested again and works as expected (with vscode-python extension installed in parallel).
Closing as this should be resolved, but please reopen if that's not the case.

**Closed by mre** 2022-07-26 21:52 UTC
Labels: hacktoberfest-accepted
